services:
  - type: web
    name: resume-ai-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /actuator/health
